spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 52choiinsuk
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
server:
  port: 9092