spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 52choiinsuk
    driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#    serialization:
#      fail-on-empty-beans: false #빈값은 직렬화하지 않음
server:
  port: 9092